spring:
  application:
    name: spring

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1050MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

jwt:
  secret: ${JWT_SECRET}
  access-token-exp-min: ${JWT_ACCESS_TOKEN_EXP_MIN:60}
  refresh-token-exp-days: ${JWT_REFRESH_TOKEN_EXP_DAYS:14}

app:
  cookie:
    secure: ${COOKIE_SECURE:false}
    same-site: ${COOKIE_SAMESITE:Lax}
  security:
    allowed-origins: [ "http://localhost:5173" ]
  upload:
    base-dir: uploads
    max-file-mb: 1024
    allowed-ext: [ mp4, webm, mov ]
    chunk-size-bytes: 1048576   # 1MB
  youtube:
    api-key: ${YOUTUBE_API_KEY:YOUR_YOUTUBE_API_KEY}
  signed-url:
    secret: ${SIGNED_URL_SECRET}
    ttl-seconds: ${SIGNED_URL_TTL_SECONDS:120}
  frontend-base-url: ${FRONTEND_BASE_URL:http://localhost:5173}


